version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
  build:
    commands:
      - echo Build started on `date`
      - echo test should be here...

      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t alihewaigh/dkr-container-app-client ./client
      - docker build -t alihewaigh/dkr-container-app-backend ./backend
      - docker build -t alihewaigh/dkr-container-app-nginx ./nginx
      # Log in to the Docker CLI
      - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push alihewaigh/dkr-container-app-client
      - docker push alihewaigh/dkr-container-app-backend
      - docker push alihewaigh/dkr-container-app-nginx
